#!/bin/zsh



function clearScreen() {
    # CLEAR SCREEN AND SET CURSOR ON TOP
    echo "\x1b[2J"
    echo "\x1b[H"
}

function init() {
    
    cd /Users/diegoibarra/Developer/1_myProjects/Apps/ToDo

    echo "\n---------------------------">>resources/cache/diegoibarra.todo.err
    date +%m-%d>>resources/cache/diegoibarra.todo.err

    echo "\n---------------------------" >> resources/cache/diegoibarra.todo.out
    date +%m-%d >> resources/cache/diegoibarra.todo.out

    ITEM_LIST=()
    LOOP=true
    HEIGHT=$(tput lines)
    
    # CHANGE FONT COLOR
    echo "\x1b[38;5;202m"

    clearScreen
}

function showTasks() {
    clearScreen
    task_str=$(sed 's/,/  -  /' TaskList.csv)
    echo $task_str
    echo "\x1b[${HEIGHT}B"
    read -q "CONTINUE?Continue? (enter: no; y: yes): "
    if [[ "$CONTINUE" == "y" ]]; then 
        clearScreen
    fi
    if [[ "$CONTINUE" == "n" ]]; then 
        clearScreen
        exit
    fi
}

####################################################################

init

while true; do
    read "INPUT?: "
    case "${INPUT}" in
    "" | " " | "q" | "quit" | "-q" | "-quit" )
        break
    ;;
    "list" | "l" | "-list" | "-l" )
        showTasks;
    ;;
    "update" )
        ITEM_LIST="update"
    ;;
    * )
        ITEM_LIST+=($INPUT)
    ;;
    esac
done
    
nohup python3 makeTasks.py $ITEM_LIST >>resources/cache/diegoibarra.todo.out 2>>resources/cache/diegoibarra.todo.err &

sleep 4
echo "\x1b[0m"
exit
