#!/bin/zsh

# ▗▄▄▄▖▗▖ ▗▖▗▖  ▗▖ ▗▄▄▖▗▄▄▄▖▗▄▄▄▖ ▗▄▖ ▗▖  ▗▖ ▗▄▄▖
# ▐▌   ▐▌ ▐▌▐▛▚▖▐▌▐▌     █    █  ▐▌ ▐▌▐▛▚▖▐▌▐▌   
# ▐▛▀▀▘▐▌ ▐▌▐▌ ▝▜▌▐▌     █    █  ▐▌ ▐▌▐▌ ▝▜▌ ▝▀▚▖
# ▐▌   ▝▚▄▞▘▐▌  ▐▌▝▚▄▄▖  █  ▗▄█▄▖▝▚▄▞▘▐▌  ▐▌▗▄▄▞▘
# ##########################################################################

function consoleSetUp() {
    EXE_PATH="$1"
    SCRIPT_DIR=$(dirname $EXE_PATH)
    cd $SCRIPT_DIR
    PYTHON_VENV="/Users/diegoibarra/.config/pyenv/versions/3.13.0/envs/ToDo/bin/python"
    ITEM_LIST=()
    PYTHON_SCRIPT="makeTasks.py"
    HEIGHT=$(tput lines)
    
    clearScreen
    
    # CHANGE FONT COLOR
    echo "\x1b[1A\x1b[38;5;244m  Task     -     Date"
    echo "\x1b[1A\x1b[38;5;202m"

} ###############################################

function clearScreen() {
    # CLEAR SCREEN AND SET CURSOR ON TOP
    echo "\x1b[2J"
    echo "\x1b[H"
    echo "\x1b[3A"
} ###############################################

function showTasks() {
    clearScreen
    task_str=$(sed 's/,/  -  /' TaskList.csv)
    echo $task_str
    echo "\x1b[${HEIGHT}B"
    read -q "CONTINUE?Continue? (enter: no; y: yes): "
    clearScreen
    
} ###############################################


#  ▗▄▄▖▗▄▄▄▖▗▄▖ ▗▄▄▖▗▄▄▄▖
# ▐▌     █ ▐▌ ▐▌▐▌ ▐▌ █  
#  ▝▀▚▖  █ ▐▛▀▜▌▐▛▀▚▖ █  
# ▗▄▄▞▘  █ ▐▌ ▐▌▐▌ ▐▌ █
# ##########################################################################

consoleSetUp $0

while true; do
    read "INPUT?: "
    case "${INPUT}" in
    "" | " " | "q" | "quit" | "-q" | "-quit" )
        break
    ;;
    "list" | "l" | "-list" | "-l" )
        showTasks;
        if [ $CONTINUE = "y" ]; then
            consoleSetUp $EXE_PATH
        else
            break
        fi
    ;;
    "open" | "tasks" )
        open TaskList.csv
    ;;
    "vscode" | "code" )
        code $SCRIPT_DIR
        break
    ;;
    "update" )
        PYTHON_SCRIPT="makeUpdate.py"
        break
    ;;
    * )
        ITEM_LIST+=($INPUT)
        PYTHON_SCRIPT="makeTasks.py"
    ;;
    esac
done

nohup $PYTHON_VENV $PYTHON_SCRIPT $ITEM_LIST > /dev/null 2>&1 &


# echo "\x1b[0m"
# exit
############################################################################
############################################################################
############################################################################